class ScanSignalConnectorMixin:
    def _connect_signals(self):
        self._connect_folder_signals()
        self._connect_preview_signals()
        self._connect_log_signals()

    def _connect_folder_signals(self):
        self.folder_section.folder_select_button.clicked.connect(
            self.actions.select_folder
        )
        self.folder_section.preview_button.clicked.connect(
            self.actions.start_preview
        )
        self.folder_section.scan_button.clicked.connect(
            self.actions.start_scan
        )
        self.folder_section.pause_button.clicked.connect(
            self.actions.pause_scan
        )
        self.folder_section.resume_button.clicked.connect(
            self.actions.resume_scan
        )
        self.folder_section.stop_button.clicked.connect(
            self.actions.stop_scan
        )

    def _connect_preview_signals(self):
        self.preview_select_all_button.clicked.connect(
            self.preview_table.select_all_available
        )
        self.preview_clear_selection_button.clicked.connect(
            self.preview_table.clear_all_selection
        )
        self.preview_exclude_selected_button.clicked.connect(
            self.preview_table.exclude_selected_rows
        )
        self.preview_keep_selected_button.clicked.connect(
            self.preview_table.keep_selected_rows_only
        )
        self.preview_exclude_error_button.clicked.connect(
            self.preview_table.exclude_error_rows
        )
        self.preview_export_csv_button.clicked.connect(
            self.actions.export_preview_results_csv
        )
        self.preview_export_non_artwork_txt_button.clicked.connect(
            self.actions.export_non_artwork_files_txt
        )
        self.preview_export_non_artwork_csv_button.clicked.connect(
            self.actions.export_non_artwork_files_csv
        )
        self.preview_scan_selected_button.clicked.connect(
            self.actions.start_selected_preview_items_scan
        )
        self.preview_show_created_checkbox.toggled.connect(
            self.actions.apply_preview_filters
        )
        self.preview_show_updated_checkbox.toggled.connect(
            self.actions.apply_preview_filters
        )
        self.preview_show_error_checkbox.toggled.connect(
            self.actions.apply_preview_filters
        )
        self.preview_hide_unchanged_checkbox.toggled.connect(
            self.actions.apply_preview_filters
        )
        self.preview_table.selection_changed.connect(
            self._update_preview_summary
        )

    def _connect_log_signals(self):
        self.clear_log_button.clicked.connect(
            self.actions.clear_scan_results
        )
        self.result_filter_combo.currentTextChanged.connect(
            self.actions.apply_result_filter
        )
        self.error_only_checkbox.toggled.connect(
            self.actions.apply_error_only_filter
        )
        self.retry_failed_button.clicked.connect(
            self.actions.retry_failed_items
        )
        self.clear_failed_button.clicked.connect(
            self.actions.clear_failed_items
        )
        self.export_failed_csv_button.clicked.connect(
            self.actions.export_failed_items_csv
        )
        self.export_all_csv_button.clicked.connect(
            self.actions.export_all_scan_results_csv
        )
        self.log_table.artist_open_requested.connect(
            self.actions.open_artist_detail
        )
        self.log_table.folder_open_requested.connect(
            self.actions.open_folder
        )
