DEFAULT_UPDATE_CHECK_REQUEST_INTERVAL_MS = 1000
DEFAULT_UPDATE_CHECK_BATCH_SIZE = 20
DEFAULT_UPDATE_CHECK_BATCH_REST_MS = 180000

MIN_UPDATE_CHECK_REQUEST_INTERVAL_MS = 0
MIN_UPDATE_CHECK_BATCH_SIZE = 1
MIN_UPDATE_CHECK_BATCH_REST_MS = 0
